# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [18.x, 20.x, 22.x]
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm set "https://github.com/rmorrow/rdicidr-0.1.0.git:_authToken=$TOKEN_GITHUB"
    - run: npm run lint
    - run: npm install -g prettier
    - run: npm install npx    
    - run: npx prettier . --write
    #- run: npm run prettier --write .
    #- run: npm run build --if-present
    - run: npm run build 
    - run: npm test
    - run: CI=true npm run test
    #- run: npm adduser
    #- run: npm publish
    #- run: 
       #echo @lexacode:https://npm.pkg.github.com/ > .npmrc
       #echo 'https://github.com/rmorrow/rdicidr-0.1.0.git:_authToken=$TOKEN_GITHUB' >> .npmrc
    #- run: npm publish
      #working-directory: ./
     # env:
      # NODE_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}  
    - name: Remove existing artifacts from AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 rm \
        s3://fullstackassessment \
        --recursive \
        --region ap-southeast-2
    - name: Deploy artifacts to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        ./build s3://fullstackassessment \
        --recursive \
        --acl public-read \
        --region ap-southeast-2      

